-- ==========================================
-- LANKASHOP ELITE - COMPLETE DATABASE SCHEMA
-- DATABASE: PostgreSQL (Supabase)
-- PURPOSE: Production-ready schema with RLS, Triggers, and Indexes
-- ==========================================

-- 0. Extensions & Setup
create extension if not exists "uuid-ossp";

-- 1. Profiles Table (Extends Supabase Auth)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text unique,
  full_name text,
  role text default 'user' check (role in ('user', 'admin')),
  phone text,
  address text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Products Table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  category text not null,
  price decimal(10,2) not null check (price >= 0),
  original_price decimal(10,2) check (original_price >= price),
  stock integer default 0 check (stock >= 0),
  image_url text,
  is_featured boolean default false,
  discount_percent integer default 0 check (discount_percent >= 0 and discount_percent <= 100),
  specifications jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Orders Table
create table if not exists public.orders (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) on delete set null,
  order_number text unique not null,
  total_amount decimal(10,2) not null check (total_amount >= 0),
  status text default 'pending' check (status in ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled')),
  whatsapp_number text,
  shipping_address text,
  tracking_number text,
  payment_method text default 'cod',
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Order Items Table (Normalized)
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid references public.orders(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete set null,
  quantity integer default 1 check (quantity > 0),
  price_at_time decimal(10,2) not null check (price_at_time >= 0),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Cart Items Table (Persistent Cart)
create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete cascade not null,
  quantity integer default 1 check (quantity > 0),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id)
);

-- 6. Wishlists Table
create table if not exists public.wishlists (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id)
);

-- 7. Reviews Table
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete cascade not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text,
  is_verified_purchase boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id)
);

-- 8. Discount Codes Table
create table if not exists public.discounts (
  id bigint generated by default as identity primary key,
  code text unique not null,
  description text,
  discount_percent integer not null check (discount_percent > 0 and discount_percent <= 100),
  max_uses integer check (max_uses > 0),
  used_count integer default 0 check (used_count >= 0),
  min_order_value decimal(10,2) default 0 check (min_order_value >= 0),
  valid_from timestamp with time zone default now(),
  valid_until timestamp with time zone,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 9. Notifications Table
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  message text,
  type text default 'system' check (type in ('system', 'order', 'promotion', 'alert')),
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 10. Feedback/Contact Table
create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS)
-- ==========================================

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.cart_items enable row level security;
alter table public.wishlists enable row level security;
alter table public.reviews enable row level security;
alter table public.discounts enable row level security;
alter table public.notifications enable row level security;
alter table public.feedback enable row level security;

-- Security Helper Functions
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
end;
$$ language plpgsql security definer;

-- Profiles Policies
create policy "Profiles are viewable by everyone" on public.profiles for select using (true);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- Products Policies
create policy "Products are viewable by everyone" on public.products for select using (true);
create policy "Admins can manage products" on public.products for all using (public.is_admin());

-- Orders Policies
create policy "Users can view own orders" on public.orders for select using (auth.uid() = user_id);
create policy "Users can create orders" on public.orders for insert with check (auth.uid() = user_id);
create policy "Admins can view and update all orders" on public.orders for all using (public.is_admin());

-- Order Items Policies
create policy "Users can view own order items" on public.order_items for select using (
  exists (select 1 from public.orders where id = public.order_items.order_id and user_id = auth.uid())
);
create policy "Users can create order items" on public.order_items for insert with check (
  exists (select 1 from public.orders where id = public.order_items.order_id and user_id = auth.uid())
);
create policy "Admins can manage all order items" on public.order_items for all using (public.is_admin());

-- Cart Items Policies
create policy "Users can manage own cart" on public.cart_items for all using (auth.uid() = user_id);

-- Wishlists Policies
create policy "Users can manage own wishlist" on public.wishlists for all using (auth.uid() = user_id);

-- Reviews Policies
create policy "Reviews are viewable by everyone" on public.reviews for select using (true);
create policy "Users can create and update own reviews" on public.reviews for all using (auth.uid() = user_id);
create policy "Admins can manage all reviews" on public.reviews for all using (public.is_admin());

-- Discounts Policies
create policy "Discounts are viewable by everyone" on public.discounts for select using (is_active = true);
create policy "Admins can manage discounts" on public.discounts for all using (public.is_admin());

-- Notifications Policies
create policy "Users can view own notifications" on public.notifications for select using (auth.uid() = user_id);
create policy "Users can update own notifications" on public.notifications for update using (auth.uid() = user_id);
create policy "Admins can manage all notifications" on public.notifications for all using (public.is_admin());

-- Feedback Policies
create policy "Anyone can submit feedback" on public.feedback for insert with check (true);
create policy "Admins can view feedback" on public.feedback for select using (public.is_admin());

-- ==========================================
-- TRIGGERS & FUNCTIONS
-- ==========================================

-- 1. Update updated_at timestamps
create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_profiles_updated_at before update on public.profiles for each row execute procedure public.update_updated_at_column();
create trigger update_products_updated_at before update on public.products for each row execute procedure public.update_updated_at_column();
create trigger update_orders_updated_at before update on public.orders for each row execute procedure public.update_updated_at_column();
create trigger update_cart_items_updated_at before update on public.cart_items for each row execute procedure public.update_updated_at_column();
create trigger update_reviews_updated_at before update on public.reviews for each row execute procedure public.update_updated_at_column();

-- 2. Handle New User Registration
create or replace function public.handle_new_user() 
returns trigger as $$
declare
  is_first_user boolean;
begin
  select count(*) = 0 into is_first_user from public.profiles;
  
  insert into public.profiles (id, email, full_name, role, avatar_url)
  values (
    new.id, 
    new.email, 
    coalesce(new.raw_user_meta_data->>'full_name', new.email), 
    case when is_first_user then 'admin' else 'user' end,
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new auth user
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3. Stock Management Trigger
create or replace function public.decrement_stock_on_order()
returns trigger as $$
begin
  update public.products
  set stock = stock - new.quantity
  where id = new.product_id;
  return new;
end;
$$ language plpgsql;

create trigger on_order_item_created
  after insert on public.order_items
  for each row execute procedure public.decrement_stock_on_order();

-- ==========================================
-- INDEXES FOR PERFORMANCE
-- ==========================================

create index if not exists idx_products_category on public.products(category);
create index if not exists idx_products_featured on public.products(is_featured) where is_featured = true;
create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_reviews_product_id on public.reviews(product_id);
create index if not exists idx_cart_items_user_id on public.cart_items(user_id);
create index if not exists idx_notifications_user_id_unread on public.notifications(user_id) where is_read = false;
create index if not exists idx_discounts_code on public.discounts(code);
