-- 1. Create reviews table if not exists
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete cascade not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for reviews
alter table public.reviews enable row level security;
create policy "Reviews are viewable by everyone" on public.reviews for select using (true);
create policy "Users can insert own reviews" on public.reviews for insert with check (auth.uid() = user_id);
create policy "Admins can delete reviews" on public.reviews for delete using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

-- 2. Create coupons table
create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text unique not null,
  discount_percent integer not null check (discount_percent > 0 and discount_percent <= 100),
  is_active boolean default true,
  expiry_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for coupons
alter table public.coupons enable row level security;
create policy "Coupons read access" on public.coupons for select using (true);
create policy "Admins full access coupons" on public.coupons for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

-- 3. Add stock_quantity column to products
do $$ 
begin 
    if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'stock_quantity') then 
        alter table public.products add column stock_quantity integer default 0 check (stock_quantity >= 0);
        -- Migrate existing stock to stock_quantity if 'stock' column exists
        -- Assuming 'stock' column exists based on previous schema
        update public.products set stock_quantity = stock;
    end if; 
end $$;
