-- ==========================================
-- LANKASHOP ELITE - FINAL DATABASE SCHEMA
-- CONTEXT: Sri Lankan E-commerce Store
-- ==========================================

-- 1. Enable UUID extension
create extension if not exists "uuid-ossp";

-- 2. Create Tables

-- PROFILES (Extends Auth Users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  avatar_url text,
  role text default 'user' check (role in ('user', 'admin')),
  phone text,
  address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- PRODUCTS (Currency: LKR)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price_lkr numeric(12,2) not null check (price_lkr >= 0),
  stock integer default 0 check (stock >= 0),
  category text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ORDERS
create table if not exists public.orders (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) on delete set null,
  status text default 'pending' check (status in ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
  total_lkr numeric(12,2) not null check (total_lkr >= 0),
  shipping_address text not null,
  payment_method text default 'cod', -- Cash on Delivery is popular in SL
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ORDER ITEMS
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid references public.orders(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete set null,
  quantity integer default 1 check (quantity > 0),
  price_at_purchase numeric(12,2) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- REVIEWS
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete cascade not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- COUPONS
create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text unique not null,
  discount_percent integer not null check (discount_percent > 0 and discount_percent <= 100),
  active boolean default true,
  expiry_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Row Level Security (RLS) & Policies

-- Helper function to check for admin role
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
end;
$$ language plpgsql security definer;

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.reviews enable row level security;
alter table public.coupons enable row level security;

-- PROFILES Policies
create policy "Public profiles are viewable by everyone" on public.profiles for select using (true);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- PRODUCTS Policies
create policy "Products are viewable by everyone" on public.products for select using (true);
create policy "Admins can insert products" on public.products for insert with check (public.is_admin());
create policy "Admins can update products" on public.products for update using (public.is_admin());
create policy "Admins can delete products" on public.products for delete using (public.is_admin());

-- ORDERS Policies
create policy "Users can view own orders" on public.orders for select using (auth.uid() = user_id);
create policy "Admins can view all orders" on public.orders for select using (public.is_admin());
create policy "Users can insert own orders" on public.orders for insert with check (auth.uid() = user_id);
create policy "Admins can update orders" on public.orders for update using (public.is_admin());

-- ORDER ITEMS Policies
create policy "Users can view own order items" on public.order_items for select using (
  exists (select 1 from public.orders where id = public.order_items.order_id and user_id = auth.uid())
);
create policy "Admins can view all order items" on public.order_items for select using (public.is_admin());
create policy "Users can insert order items" on public.order_items for insert with check (
  exists (select 1 from public.orders where id = public.order_items.order_id and user_id = auth.uid())
);

-- REVIEWS Policies
create policy "Reviews are viewable by everyone" on public.reviews for select using (true);
create policy "Users can insert own reviews" on public.reviews for insert with check (auth.uid() = user_id);
create policy "Admins can delete reviews" on public.reviews for delete using (public.is_admin());

-- COUPONS Policies
create policy "Coupons are viewable by everyone" on public.coupons for select using (true); -- Usually need to read code to validate
create policy "Admins full access coupons" on public.coupons for all using (public.is_admin());

-- 4. Storage Policies (Bucket: 'products')

-- Ensure bucket exists (Note: In SQL editor this might fail if exists, typically done via UI or migration script logic, here standard SQL approach)
insert into storage.buckets (id, name, public) 
values ('products', 'products', true)
on conflict (id) do nothing;

-- Storage Policies
create policy "Public Access" on storage.objects for select using ( bucket_id = 'products' );
create policy "Admin Upload" on storage.objects for insert with check ( bucket_id = 'products' and public.is_admin() );
create policy "Admin Update" on storage.objects for update using ( bucket_id = 'products' and public.is_admin() );
create policy "Admin Delete" on storage.objects for delete using ( bucket_id = 'products' and public.is_admin() );

-- 5. Triggers (User Sign-up)

create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', 'user');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger logic
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
